name: Build and Test

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NODE_VERSION: 18
  CACHE_KEY: "${{ github.ref }}-${{ github.run_id }}-${{ github.run_attempt }}"

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          node: ${{ env.NODE_VERSION }}

      - name: Save build artifacts
        uses: actions/cache/save@v4
        with:
          path: .
          key: ${{ env.CACHE_KEY }}

  unit:
    needs: build # Require build to complete before running tests

    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare
        with:
          node: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE_KEY }}

      - run: npm test

      - uses: codecov/codecov-action@6d798873df2b1b8e5846dba6fb86631229fbcb17 # pin@4.4.0

  lint:
    needs: build # Require build to complete before running tests

    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare
        with:
          node: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE_KEY }}

      - run: npm run lint
